---
openvpn_packages:
  - openvpn
  - easy-rsa

openvpn_client_cert_expires: 30

openvpn_routes: []
openvpn_clients: []

openvpn_path: /etc/openvpn
openvpn_path_easyrsa: "{{ openvpn_path }}/easyrsa"
openvpn_path_clients: "{{ openvpn_path }}/client-configs"
openvpn_path_clients_local: "{{ _ | mandatory('openvpn_path_clients_local definition is mandatory') }}"
openvpn_server_remote_host: "{{ _ | mandatory('openvpn_server_remote_host definition is mandatory') }}"
openvpn_server_interface: eth0

openvpn_key_country: "US"
openvpn_key_province: "California"
openvpn_key_city: "Beverly Hills"
openvpn_key_org: "ACME CORPORATION"
openvpn_key_ou: "Anvil Department"
openvpn_key_email: "user@example.com"
openvpn_key_server_cn: "OpenVPN"
