---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  register: apt_res
  retries: 5
  until: apt_res is success
  changed_when: false

- name: Install openvpn packages
  ansible.builtin.package:
    name: "{{ openvpn_packages }}"
    state: present
