---
- name: Copy PKI files to /etc/openvpn/server
  ansible.builtin.copy:
    src: "{{ openvpn_path }}/pki/{{ item }}"
    dest: /etc/openvpn/server/{{ item | basename }}
    mode: "0640"
    remote_src: true
  loop:
    - ca.crt
    - dh.pem
    - ta.key
    - issued/server.crt
    - private/ca.key
    - private/server.key

- name: Set net.ipv4.ip_forward to 1
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
    ignoreerrors: true

- name: Place rc.local
  ansible.builtin.template:
    src: rc.local.j2
    dest: "/etc/rc.local"
    owner: root
    group: root
    mode: "0755"

- name: Run rc.local once
  ansible.builtin.command: /etc/rc.local
  changed_when: false

- name: Place server.conf
  ansible.builtin.template:
    src: server.conf.j2
    dest: "{{ openvpn_path }}/server.conf"
    owner: root
    group: nogroup
    mode: "0640"
  notify:
    - Restart openvpn

- name: Enable openvpn service
  ansible.builtin.service:
    name: openvpn@server.service
    enabled: true
  notify:
    - Restart openvpn
