---    
prometheus_scrape_configs:
  - job_name: "prometheus"
    metrics_path: "{{ prometheus_metrics_path }}"
    static_configs:
      - targets:
          - "{{ ansible_fqdn | default(ansible_host) | default('localhost') }}:9090"
  - job_name: "node"
    static_configs:
      - targets:
        - "{{ hostvars['plex']['ansible_host'] }}:9100"
        - "{{ hostvars['grafana']['ansible_host'] }}:9100"
        - "{{ hostvars['prometheus']['ansible_host'] }}:9100"
  - job_name: homeassistant
    metrics_path: /api/prometheus
    bearer_token: "{{ homeassistant_token | mandatory }}"
    static_configs:
      - targets:
          - "homeassistant.lab.home:8123"
