---
- name: Install Prometheus server
  hosts: prometheus
  roles:
    - prometheus.prometheus.prometheus
  vars:
    prometheus_scrape_configs:
      - job_name: "prometheus"
        metrics_path: "{{ prometheus_metrics_path }}"
        static_configs:
          - targets:
              - "{{ ansible_fqdn | default(ansible_host) | default('localhost') }}:9090"
      - job_name: "node"
        static_configs:
          - targets: "{{ groups['node_exporter_scrape_targets'] | map('extract', hostvars, ['ansible_host']) | product([':9100']) | map('join') | list }}"
      - job_name: homeassistant
        metrics_path: /api/prometheus
        bearer_token: "{{ homeassistant_token | mandatory }}"
        static_configs:
          - targets:
              - "homeassistant.lab.home:8123"
